---
abstract: "Business::CPI's PayPal driver"
author:
  - 'André Walker <andre@andrewalker.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CPI-Gateway-PayPal
requires:
  Business::CPI: 0.5
  Business::PayPal::NVP: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  LWP::UserAgent: 0
  Moo: 0
  perl: 5.008
resources:
  repository: git://github.com/andrewalker/p5-business-cpi-gateway-paypal.git
version: 0.901
